version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  EnableNuGetPackageRestore: true
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  project: AzureStorageTableExternalLoginStore.sln
  publish_nuget: true
  verbosity: minimal
after_build:
- ps: .\build\pack.ps1
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/alexlindgren/api/v2/package
  api_key:
    secure: Ch+m53TO3H7V3zKq9WnIGjIh6r+VBkblVsulyuwmOsBC9dazfZnFgYPM0XQNy22L
  symbol_server: https://www.myget.org/F/alexlindgren/symbols/api/v2/package
  on:
    branch: develop
- provider: NuGet
  api_key:
    secure: f2SKgprrXxQ8sKI2IMxBSYvEcsrDHiGAJ9yUAnUT316QvghSvDmQORTHYgVaKu80
  on:
    branch: master
notifications:
- provider: Email
  to:
  - alexlindgren@outlook.com
  subject: umbracoidentity-azureloginstore build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true